kind: Deployment
apiVersion: apps/v1

metadata:
  name: demodeployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: httpd
  template:
     metadata:
        labels:
          app: httpd
     spec:
        containers:
          - name: dep
            image: nirmaldocker1987/k8s
            imagePullPolicy: Always
            ports:
              - containerPort: 80


---
kind: Service
apiVersion: v1
metadata:
  name: myservice
spec:
  selector:
    app: httpd
  ports:
      - name: nirmal
        protocol: TCP
        port: 9000
        targetPort: 80

  type: NodePort
